Member#3 game development
Marcraphael12/Catalog-of-my-things pull request #37
Opened 2023-05-04 14:10 UTC by Marcraphael12

In this project, we are performing test on authors and game objects
    - add_item method in the Author class
        - should take an instance of the Item class as an input
        - should add the input item to the collection of items
        - should add self as a property of the item object (by using the correct setter from the item object)
    - can_be_archived?() in the Game class
        - should override the method from the parent class
        - should return true if parent's method returns true AND if last_played_at is older than 2 years
        - otherwise, it should return false
- Add unit tests for all implemented methods.
- The following options should be available:
    - List of games
    - List all authors (e.g. 'Stephen King')
    - Add a game
 - All data should be preserved by saving collections in .json files.
 - Create a schema.sql file with tables that will be analogical to the structure of the classes that you created:
    - games table (add all properties and associations from the parent Item class as table columns)
    - authors table

Happy review!

2023-05-04 18:15 UTC, rica213 requested changes
Hi @Marcraphael12  

Great job so far. Your effort is showing in your code. I especially appreciate how you document your code👌🏽 
Nevertheless, there are some issues I reckon you should address. You can check them in the comments below. If you have any comments to add or if something is unclear, kindly tag me.

# 🟡 STATUS: REQUIRED CHANGES 

## Highlights
Good Design ✔️
Professional Documentation ✔️
No Linter errors ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 07:43 UTC, Marcraphael12 commented on classes/game_sub_classes/game_actions.rb
> +    if File.exist?(file)
hey @rica213, thanks for the feedback!
I make sure that the file is never empty by storing an array in it in case no data is provided

2023-05-05 07:43 UTC, Marcraphael12 commented on classes/game_sub_classes/game_actions.rb
> +    if File.exist?(file)
kindly check the answer above

2023-05-05 07:46 UTC, Marcraphael12 commented on database/game_schema.sql
Sorry about game_db.sql, I wanted to rename it as game_schema.sql

2023-05-05 07:48 UTC, Marcraphael12 commented on database/item_schema.sql
you're right, I did it just to create the author and game table so we can combine them into one file

2023-05-05 12:31 UTC, merged