Develop
Marcraphael12/Catalog-of-my-things pull request #43
Opened 2023-05-05 17:17 UTC by hakichris

[Video Walkthrough](https://drive.google.com/file/d/1dGZ8XjP7qJ_J2JurZg3jBi_AEB2kRVEU/view?usp=share_link)
This project is a group project, a team of three people.
The project is implemented using Ruby. 
During this week, here is the list of things we have done.

- The project is based on the given UML diagram
- List all books
- List all music albums
- List of games
- List all genres (e.g 'Comedy', 'Thriller')
- List all labels (e.g. 'Gift', 'New')
- List all authors (e.g. 'Stephen King')
- Add a book
- Add a music album
- Add a game
- Create unit tests for all implemented methods
- Write/Read from files
- Create a console app entry-point 
- Create a database analogical to the structure of the application
- Follow General Requirements
- Create a professional Readme file
- Provide a demo video (cf. at the top)

That's it 🤷🏽 
Happy Review! 👁️‍🗨️

2023-05-05 19:49 UTC, danmainah requested changes
Hi @hakichris @Marcraphael12 and @rica213 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good design on the user interface
✔️  Good professional PR and Description
✔️ Professional README file.


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-05 19:49 UTC, danmainah commented on spec/music_test_spec.rb
> +  end
- [ ] @team great work on your tests they are all passing, however, I didn't see tests for the `to_json(*args)` and `self.from_json(string)` methods in your music class, I would recommend you add them.
- [ ] @team I didn't manage to see tests for the Item, App, Source, Bookdata, and GameActions classes. it was part of the project requirement to implement unit tests for all methods in your classes as shown in the highlighted section below
![image](https://user-images.githubusercontent.com/61408860/236553040-b73e0d90-300e-486a-a4c2-65fa9d8345d7.png)

2023-05-05 19:49 UTC, danmainah commented on database/schema.sql
> +  name varchar(255)
- [ ] @team great work on your schema, however, you forgot to add a foreign key referencing the item table like you did in the authors table.

2023-05-05 19:49 UTC, danmainah commented on database/schema.sql
> +  color varchar(50)
@team great work on your schema, however, you forgot to add a foreign key referencing the item table like you did in the authors table.

2023-05-06 14:02 UTC, hakichris commented on database/schema.sql
> +  name varchar(255)
Thank you @danmainah, we rectified according to your recommendation

2023-05-06 14:02 UTC, hakichris commented on database/schema.sql
> +  color varchar(50)
Thank you @danmainah, we rectified according to your recommendation

2023-05-06 14:02 UTC, hakichris commented on spec/music_test_spec.rb
> +  end
Thank you @danmainah, we rectified according to your recommendation

2023-05-06 14:22 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @Marcraphael12, @hakichris, and @rica213👋, 

### You did a marvelous job on the Ruby group capstone project and this is one of the best projects I have seen so far!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Uploading image.png…]()

## To Highlight 🎉
- All tests are passed. ✔️
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Highly organized code. ✔️
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 14:31 UTC, merged